### ISSUE TITLE
docker-compose up fails while creating social_cron service

### ISSUE THREAD

**Issue by jerrac** [goalgorilla/drupal_social#324] opened 2017-11-01 22:08 UTC
I just checked out this repository in an effort to test open social. When running docker-compose up, it errors out while creating social_cron.

```bash
Creating volume "drupalsocial_db_data" with default driver
Pulling mailcatcher (schickling/mailcatcher:latest)...
latest: Pulling from schickling/mailcatcher
88286f41530e: Pull complete
646f42db9346: Pull complete
85e6f1a7a21f: Pull complete
b6573fe11cb6: Pull complete
acbba1ba745a: Pull complete
0b601fe3129a: Pull complete
Digest: sha256:6cdbe7096b868d493897627bf04b7e51ae56f83a680c3103a0fc87409073b021
Status: Downloaded newer image for schickling/mailcatcher:latest
Pulling db (mysql:5.6)...
5.6: Pulling from library/mysql
85b1f47fba49: Already exists
27dc53f13a11: Pull complete
095c8ae4182d: Pull complete
0972f6b9a7de: Pull complete
a11a67190c24: Pull complete
908252bea0ce: Pull complete
870c4f4d5e5c: Pull complete
af57a14b554f: Pull complete
e256381aeb29: Pull complete
605c1ff4d198: Pull complete
Digest: sha256:ff19ef62a65548e7bd5440ce0e2a76f0a90ab376d953abd60709766f77969d63
Status: Downloaded newer image for mysql:5.6
Pulling web (goalgorilla/open_social_docker:dev)...
dev: Pulling from goalgorilla/open_social_docker
85b1f47fba49: Already exists
66e22dddbf92: Already exists
bf0df491fd2e: Already exists
425226034711: Already exists
5ba5c1815115: Already exists
98ab63dc099c: Already exists
389f9436e431: Already exists
d5bc131d410e: Already exists
27cdaa072a89: Pull complete
cfaf1528d144: Pull complete
62966ca13a7f: Pull complete
036e2f2f8687: Pull complete
a9a55a6b9503: Pull complete
864c9d34dea6: Pull complete
19d5959de62d: Pull complete
cdf83984eeaa: Pull complete
a950a7e5647a: Pull complete
00db1b7c4173: Pull complete
1fb0280680a9: Pull complete
1ed662f50174: Pull complete
9e94eb83c494: Pull complete
4538d270dc98: Pull complete
e7c6c8d9a06d: Pull complete
c968120d3bc3: Pull complete
495254bc974e: Pull complete
ddae4fdc156c: Pull complete
1bfc5b7db450: Pull complete
73fe997957a1: Pull complete
de7c4a8fc9b0: Pull complete
21f164697de9: Pull complete
577e07e74ec0: Pull complete
2bd99f18c0f1: Pull complete
c4fcfe343625: Pull complete
80ee3cd8076b: Pull complete
d1ea9a40bbf2: Pull complete
f1cebd9a7a47: Pull complete
ff15375b7ea7: Pull complete
a15e79817bde: Pull complete
7dbe2205f094: Pull complete
8c2f434a7fd9: Pull complete
17f11a37e4a6: Pull complete
7abbabe2c5b9: Pull complete
8900e9e95e4d: Pull complete
29e9a38249cb: Pull complete
92a8f6432b8e: Pull complete
90f95e411df3: Pull complete
85b43fa8e89c: Pull complete
2ab75a7b1e08: Pull complete
f2c65bdce1c3: Pull complete
3317a22c2264: Pull complete
Digest: sha256:62b185badfbbaa27ae52229df6176479c65cb23a999af2bd2c293f0a8c02c367
Status: Downloaded newer image for goalgorilla/open_social_docker:dev
Pulling selenium (selenium/standalone-firefox-debug:2.48.2)...
2.48.2: Pulling from selenium/standalone-firefox-debug
20d99f5aec05: Pull complete
72f7fcd433f8: Pull complete
5dce81f870ab: Pull complete
a3ed95caeb02: Pull complete
23f18164665f: Pull complete
282006c4409e: Pull complete
3472ef26cc6d: Pull complete
16de7d488a57: Pull complete
33ecbb374c0a: Pull complete
5783f1e0c823: Pull complete
a2b13c8baaf6: Pull complete
9120195b8eb8: Pull complete
9f2e386d3551: Pull complete
5377a4dfc736: Pull complete
0cb427f1f7ff: Pull complete
2e1f5c30da9a: Pull complete
ff6134da32c2: Pull complete
8fb7e242cdc5: Pull complete
77b87fcf5a92: Pull complete
599b4c0037c1: Pull complete
0ad24c051d81: Pull complete
ca1f460106f2: Pull complete
Digest: sha256:fb7d4cbcd605a2fc347ff8b7624fa1ab0980779a880de4592a72e1ac5cb143cc
Status: Downloaded newer image for selenium/standalone-firefox-debug:2.48.2
Pulling cron (goalgorilla/open_social_docker:cron)...
cron: Pulling from goalgorilla/open_social_docker
85b1f47fba49: Already exists
66e22dddbf92: Already exists
bf0df491fd2e: Already exists
425226034711: Already exists
5ba5c1815115: Already exists
98ab63dc099c: Already exists
389f9436e431: Already exists
d5bc131d410e: Already exists
27cdaa072a89: Already exists
cfaf1528d144: Already exists
62966ca13a7f: Already exists
036e2f2f8687: Already exists
a9a55a6b9503: Already exists
864c9d34dea6: Already exists
19d5959de62d: Already exists
cdf83984eeaa: Already exists
a950a7e5647a: Already exists
00db1b7c4173: Already exists
1fb0280680a9: Already exists
1ed662f50174: Already exists
9e94eb83c494: Already exists
4538d270dc98: Already exists
e7c6c8d9a06d: Already exists
c968120d3bc3: Already exists
495254bc974e: Already exists
ddae4fdc156c: Already exists
1bfc5b7db450: Already exists
73fe997957a1: Already exists
de7c4a8fc9b0: Already exists
21f164697de9: Already exists
577e07e74ec0: Already exists
2bd99f18c0f1: Already exists
c4fcfe343625: Already exists
80ee3cd8076b: Already exists
7670b2cf3e39: Pull complete
c6cb55adb5de: Pull complete
02e4ff4f0e48: Pull complete
dacbf0a74cf4: Pull complete
e96b3e7a6b94: Pull complete
04f3d3a026f3: Pull complete
437f5c3046e4: Pull complete
Digest: sha256:33a90906103aae4dd08785048360cea684eae2a048826e22a7e7395924e89a7b
Status: Downloaded newer image for goalgorilla/open_social_docker:cron
Creating social_mailcatcher ... 
Creating social_db ... 
Creating social_mailcatcher
Creating social_db ... done
Creating social_cron ... 
Creating social_web ... 
Creating social_cron
Creating social_cron ... error

ERROR: for social_cron  Cannot start service cron: b'oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\\"/var/wwCreating social_web ... error

ERROR: for social_web  Cannot start service web: b'oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\\"/var/www/html\\") set in config.json failed: no such file or directory"'

ERROR: for cron  Cannot start service cron: b'oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\\"/var/www/html\\") set in config.json failed: no such file or directory"'

ERROR: for web  Cannot start service web: b'oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\\"/var/www/html\\") set in config.json failed: no such file or directory"'
ERROR: Encountered errors while bringing up the project.

```

Just in case it was the config.json permissions error I still haven't taken time to really try and fix, I ran docker-compose up with sudo. It did not help.

```bash
sudo docker-compose up
social_mailcatcher is up-to-date
social_db is up-to-date
Starting social_cron ... 
Starting social_web ... 
Starting social_cron
Starting social_cron ... error

ERROR: for social_cron  Cannot start service cron: b'oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\\"/var/wwStarting social_web ... error

ERROR: for social_web  Cannot start service web: b'oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\\"/var/www/html\\") set in config.json failed: no such file or directory"'

ERROR: for web  Cannot start service web: b'oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\\"/var/www/html\\") set in config.json failed: no such file or directory"'

ERROR: for cron  Cannot start service cron: b'oci runtime error: container_linux.go:265: starting container process caused "chdir to cwd (\\"/var/www/html\\") set in config.json failed: no such file or directory"'
ERROR: Encountered errors while bringing up the project.
```

### docker version
```
WARNING: Error loading config file: /home/user/.docker/config.json - stat /home/user/.docker/config.json: permission denied
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### docker-compose version
```
docker-compose version 1.16.1, build 6d1ac219
docker-py version: 2.5.1
CPython version: 3.5.2
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

### cat /etc/lsb-release 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

**Comment by jochemvn** [comment] 2017-11-02 07:45
Please read this: https://github.com/goalgorilla/drupal_social/issues/316

**Comment by jerrac** [comment] 2017-11-03 18:17
I had actually read that before posting.

So, even issues that do not relate to the core open social drupal code should go in the drupal issue queue? This issue only effects the docker containers.

**Comment by ronaldtebrake** [comment] 2018-09-13 12:48
Closing this as outdated since we're not able to reproduce this anymore, sorry for the inconvienence. Hope by now you were able to start up the docker cron container. If not please open up a new issue.

**Closed by ronaldtebrake** 2018-09-13 12:48 UTC
